### ISSUE TITLE
The `SugarRecord-iOS [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT`

### ISSUE THREAD

**Issue by Ged2323** [SwiftReactive/SugarRecord#181]
Hi, awesome this is such a great API.  Though I'm getting this error when trying to install the pod
I've added: pod 'SugarRecord', :git => 'https://github.com/gitdoapp/sugarrecord.git'
to the pod file though the error happens below.  I've tried adding $(inherited) to:
Header Search Paths
Other Linker Flags
Preprocessor Macros
in Project -> Target -> Build Settings
Though still the same error.  Thanks in advance if you can help.
/********************************************/
[!] The `SugarRecord-iOS [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-SugarRecord-iOS/Pods-SugarRecord-iOS.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by pepibumur** [comment]
@Ged2323 version of CocoaPods and XCode that you're using?

**Comment by Ged2323** [comment]
Hi Pedro,
I’m using Version 7.1 (7B91b) 
cocoapods -cocoapods-0.39.0
Regards Gerard

**Comment by pepibumur** [comment]
Try this:
1. In your project build settings look for **Embedded Content Contains Swift Code**
2. Update the value to other and use the flag `$(inherited)`

It seems that CocoaPods is trying to replace that value in your project but it has already a default value defined and CocoaPods warns you about that. Let me know if that helps :).

![image](https://cloud.githubusercontent.com/assets/663605/11679188/e5669662-9e4e-11e5-99ed-491fefcd357a.png)

**Comment by Ged2323** [comment]
Great mate, that worked like a charm.  Just wondering is this updated to work with iCloud?

Yours Sincerely
Gerard Grundy

**Comment by pepibumur** [comment]
Great @Ged2323 :), the defualtstorage doesn't give support to iCloud but there's a ticket to implement it. I'll let you know when it's ready. Are you using it?

**Comment by Ged2323** [comment]
Yes. I am playing around with it.  I had it fully working on the previous demo you had with the list and tableview.  Though once the Apple update it all failed. tons of errors. I’m happy to try and work through them with you if that helps.  It’s a big project!! I did try to install sugar record on an new Xcode file though I;m getting errors with the sample code you provided.  

 Use of undeclared type ‘CoreDataDefaultStorage'

Am i meant to import or drop the SugarRecord project into the new Xcode project for this to work?


Yours Sincerely
Gerard

**Comment by pepibumur** [comment]
Can you share an screenshot @Ged2323 ?

**Comment by Ged2323** [comment]
Hi Here’s the screenshot.

**Comment by pepibumur** [comment]
Can't see it @Ged2323

**Comment by Ged2323** [comment]
I updated my previous post.

**Comment by pepibumur** [comment]
@Ged2323 
```
import SugarRecord
```

**Comment by Ged2323** [comment]
Hi Pedro I gave it a go though I'm getting the same error.
And this one on the import. --> File 'ViewController.swift' is part of module 'SugarRecord'; ignoring import

![screen shot 2015-12-10 at 9 42 37 pm](https://cloud.githubusercontent.com/assets/5620610/11714583/f59bdbb2-9f86-11e5-8423-06d864e4f24e.png)

**Comment by pepibumur** [comment]
But what are you trying to do, create an example project? @Ged2323 ?

**Comment by Ged2323** [comment]
Yes I’m just trying to import sugar record onto a blank project and get it going.

**Comment by Ged2323** [comment]
I was so sad once apple updated swift.  I had an awesome project going with sugar record with iCloud and then error after error.  I tried to fix sugar record and update it to 2.1 but it was epic.
I could not find any solutions anywhere.
