### ISSUE TITLE
I need a sample example project to insert , update , delete records

### ISSUE THREAD

**Issue by aryansbtloe** [SwiftReactive/SugarRecord#185]

**Comment by pepibumur** [comment]
@aryansbtloe it will be included in the next release :)

**Comment by isaacroldan** [comment]
Is this the Santa list for this christmas? i need a girlfriend, thanks. :trollface:

**Comment by pepibumur** [comment]
@aryansbtloe https://github.com/SwiftReactive/SugarRecord/pull/186
