### ISSUE TITLE
Module SugarRecord have no member named : "applicationWillResignActive" in SugarRecord 2.1.3

### ISSUE THREAD

**Issue by iOSBeginners** [SwiftReactive/SugarRecord#187]
Hello,
I integrate SugarRecord in AppDelegate , it is the version : 2.1.3

This is my AppDelegate code

import UIKit
import CoreData
import SugarRecord

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

        self.coreDataStorage()
        return true
    }

    func applicationWillResignActive(application: UIApplication) {
        SugarRecord.applicationWillResignActive()
    }

    func applicationDidEnterBackground(application: UIApplication) {

    }

    func applicationWillEnterForeground(application: UIApplication) {

    }

    func applicationDidBecomeActive(application: UIApplication) {

    }

    func applicationWillTerminate(application: UIApplication) {

    }
    
    //MARK: SugarRecord Stack
    // Initializing CoreDataDefaultStorage
    func coreDataStorage() -> CoreDataDefaultStorage {
        let store = CoreData.Store.Named("Drive")
        let bundle = NSBundle(forClass: self.classForCoder)
        let model = CoreData.ObjectModel.Merged([bundle])
        let defaultStorage = try! CoreDataDefaultStorage(store: store, model: model)
        return defaultStorage
    }
}

I have this error : Module SugarRecord have no member named : "applicationWillResignActive"

it is the same for applicationWillEnterForeground and applicationWillTerminate

**Comment by pepibumur** [comment]
@iOSBeginners this method doesn't exists:
```
SugarRecord.applicationWillResignActive()
```
Why are you using it?

**Comment by iOSBeginners** [comment]
I read this in this link https://github.com/SwiftReactive/SugarRecord/wiki/Setup-SugarRecord
The App's lifecycle notifications part 

so now we don't need to call it the lifecycle is managed automatically ?

**Comment by pepibumur** [comment]
The Wiki is outdated, follow the steps in the README @iOSBeginners

**Comment by iOSBeginners** [comment]
@pepibumur Ok i will follow README juste correct this line : 
let bundle = NSBundle(forClass: CoreDataDefaultStorageTests.classForCoder())

With this 
let bundle = NSBundle(forClass: self.classForCoder())

thx,

**Comment by pepibumur** [comment]
Changed @iOSBeginners
