### ISSUE TITLE
Sugar record

### ISSUE THREAD

**Issue by iOSBeginners** [SwiftReactive/SugarRecord#190]
Hello,

Sugar record handle automatically migration of Data base ?

**Comment by pepibumur** [comment]
Yes @iOSBeginners , when you initialize the storage, you can pass an attribute if you want SugarRecord to **automigrate** the database schema.

**Comment by iOSBeginners** [comment]
Can you give an example because i don't find how to do it 

thx,

**Comment by pepibumur** [comment]
Here the initialization line https://github.com/SwiftReactive/SugarRecord/blob/master/SugarRecord/Source/CoreData/Storages/CoreDataDefaultStorage.swift#L101

Simply pass the last parameter as true and that should be enough.

@iOSBeginners
